/*************************************************************************
 *
 * KLEAREXPRESS CONFIDENTIAL
 * __________________
 *
 *  Copyright (c) 2018 - 2018 KlearExpress Corporation.
 *  All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of KlearExpress Corporation and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to KlearExpress Corporation
 * and its suppliers and may be covered by U.S. and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from KlearExpress Corporation.
 */

 const Images = {
    // kn_powered_logo:require("../../src/images/KN_powered_by.svg"),
    // planeInAir:require("../../src/images/planeInAir.svg"),
    // airport:require("../../src/images/airport.svg"),
    // airportIcon:require("../../src/images/airportIcon.svg"),
    // downArrowRed:require("../../src/images/down-arrow-red.svg"),
    // downArrowYellow:require("../../src/images/down-arrow-yellow.svg"),
    // redBurgermenu:require("../../src/images/redBurgerIcon.svg"),
    // yellowBurgermenu:require("../../src/images/yellowBurgerIcon.svg"),
    // blackBurgermenu:require("../../src/images/blackBurgerIcon.svg"),
    // blueBurgermenu:require("../../src/images/blueBurgerIcon.svg"),
    // jdLogistics:require("../../src/images/jdlogistics.png"),
    // shipmentIcon:require("../../src/images/shipmentIcon.svg"),
    // shipmentIconRed:require("../../src/images/shipmentIconRed.svg"),
    // planeGreen:require("../../src/images/plane_green.svg"),
    // redPlane:require("../../src/images/redPlane.svg"),
    // planeWhite: require("../../src/images/plane_white.svg"),
    // shipmentWithCircle: require("../../src/images/shipment_with_circle.svg"),
    // truckProgress: require("../../src/images/truckProgress.svg"),
    // truckPurple: require("../../src/images/truckPurple.svg"),
    // shipmentWithCircleRed: require("../../src/images/shipment_with_circle_red.svg"),
    // stockPhoto: require("../../src/images/planePhoto.png"),
    // plane: require("../../src/images/plane.svg"),
    // planeRed: require("../../src/images/planeRed.svg"),
    // ellipsis: require("../../src/images/ellipsis.svg"),
    // logout: require("../../src/images/Icon_logout.svg"),
    // message: require("../../src/images/Icon_Messages.svg"),
    // account: require("../../src/images/Icon_My_Account.svg"),
    // search: require("../../src/images/icon_search.svg"),
    // noShipment: require("../../src/images/icon _No_Shipments.png"),
    // carrierShip: require("../../src/images/icon_Carrier_Ship.svg"),
    // containerPickup: require("../../src/images/building2.svg"),
    // portIcon: require("../../src/images/Legenda_port.svg"),
    // portImage: require("../../src/images/port.svg"),
    // carrierTruck: require("../../src/images/deliverytruck.svg"),
    // close: require("../../src/images/icon_close.svg"),
    // verified: require("../../src/images/verified.svg"),
    // verifiedYellow: require("../../src/images/verified.yellow.svg"),
    // file: require("../../src/images/file.svg"),
    // person: require("../../src/images/userPic.jpg"),
    // info: require("../../src/images/info.svg"),
    // sliderArrow: require("../../src/images/Icon_Small_Arrow.svg"),
    // addUserButton: require("../../src/images/Add_User.png"),
    // cbplogo: require("../../src/images/cbp-logo.png"),
    // yellowTruck: require("../../src/images/yellow-truck.jpg"),
    // visa: require("../../src/images/icon-Visa.png"),
    // mastercard: require("../../src/images/Icon_Mastercard.png"),
    // discover: require("../../src/images/icon_Discover.png"),
    // amex: require("../../src/images/AmEx.png"),
    // missingPayment: require("../../src/images/missing-payment-data.png"),
    // bank: require("../../src/images/bank.png"),
    // exampleContainer: require("../../src/images/exampleContainer.png"),
    // containerBlue: require("../../src/images/container-ready.jpg"),
    // containerGray: require("../../src/images/container-not-ready.jpg"),
    // defaultTrucker: require("../../src/images/trucker-default.png"),
    // lsLogo: require("../../src/images/LSLogo.png"),
    // angelaAaron: require("../../src/images/AngelaAaron.jpeg"),
    // verifiedNull: require("../../src/images/verifiedNull.png"),
    // newLogo2: require("../../src/images/newlogo2.png"),
    // knLogo: require("../../src/images/Logo.png"),
    // anchor: require("../../src/images/Anchor_pictogram.svg"),
    // containerCrane: require("../../src/images/container_crane.svg"),
    // containerTruck: require("../../src/images/container_truck.svg"),
    // containerImage: require("../../src/images/container-new.svg"),
    // containerImageBlue: require("../../src/images/container-new-blue.svg"),
    // whiteWarning: require("../../src/images/white_warning.svg"),
    // yellowWarning: require("../../src/images/yellow_warning.svg"),
    // redWarning: require("../../src/images/red_warning.svg"),
    // ship: require("../../src/images/ship.svg"),
    // shipRed: require("../../src/images/shipRed.svg"),
    // ship_white: require("../../src/images/ship_white.svg"),
    // printer: require("../../src/images/printer.svg"),
    // box: require("../../src/images/box.svg"),
    // educationForm: require("../../src/images/education-form.svg"),
    // wayfairLogo: require("../../src/images/wayfair_logo.jpg"),
    // gateInGray: require("../../src/images/gate-in-gray.svg"),
    // gateOutGray: require("../../src/images/gate-out-gray.svg"),
    // gateInGreen: require("../../src/images/gate-in-green.svg"),
    // gateOutGreen: require("../../src/images/gate-out-green.svg"),
    // sandClock: require("../../src/images/sand-clock.svg"),
    // navPrevious: require("../../src/images/icons/side-arrow@2x.png"),
    // navNext: require("../../src/images/icons/down-arrow@2x.png"),
    // userGroup: require("../../src/images/icons/user-group.svg"),
    // addDocument: require("../../src/images/icons/add-document.svg"),
    // sendInvite: require("../../src/images/icons/send-invite.svg"),
    // receivedResponse: require("../../src/images/icons/receive-invite.svg"),
    // closeButton: require("../../src/images/icons/close-button.svg"),
    // sendPending: require("../../src/images/icons/send-pending.svg"),
    // baby: require("../../src/images/baby.jpg"),
    // searchIcon: require("../../src/images/search.png"),
    // burgerIcon: require("../../src/images/icons/burger-icon.png"),
    // klearNowBurger:require("../../src/images/klearNowBurger.svg"),
    // defaultUser: require("../../src/images/usersDefault.svg"),
    // downArrow: require("../../src/images/icons/down-arrow.png"),
    // shipIcon: require("../../src/images/svgIcons/ship.svg"),
    // shipIconWhite: require("../../src/images/svgIcons/ship-white.svg"),
    // containerIcon: require("../../src/images/svgIcons/container-new.svg"),
    // containerIconWhite: require("../../src/images/svgIcons/container-new-white.svg"),
    // grounded: require("../../src/images/grounded.svg"),
    // smile: require("../../src/images/smile.svg"),
    // frown: require("../../src/images/frown.svg"),
    // worker: require("../../src/images/worker.svg"),
    // shipment_circle: require("../../src/images/shipment_circle.svg"),
    // stamp_copy:require("../../src/images/stamp_copy.svg"),
    // stampCopy2:require("../../src/images/stampCopy2.svg"),
    // containerReleased:require("../../src/images/containerReleased.svg"),
    // containerHold:require("../../src/images/containerHold.svg"),
    // containerFiled:require("../../src/images/containerFiled.svg"),
    // containerPending:require("../../src/images/containerPending.svg"),
    // destination:require("../../src/images/destination.svg"),
    // completed:require("../../src/images/completed.svg"),
    // containerNew:require("../../src/images/containerNew.svg"),
    // containerBig:require("../../src/images/containerBig.svg"),
    // inTransit:require("../../src/images/inTransit.svg"),
    // ReportIcon:require("../../src/images/eye.svg"),
    // nullMan:require("../../src/images/DataNotFound.svg"),
    // airBox:require("../../src/images/air-box.svg"),
    // trucker:require("../../src/images/trucker.svg"),
    // money:require("../../src/images/money.svg"),
    // ship:require("../../src/images/ship.svg"),
    // container:require("../../src/images/container-new-blue.svg"),
    // box:require("../../src/images/box.svg"), 
    // educationForm:require("../../src/images/education-form.svg"), 
    // usaFlag:require("../../src/images/us_flag.svg"), 
    // ukFlag:require("../../src/images/UK_Flag.svg"),
    // canadaFlag:require("../../src/images/canada_flag.svg"),
    // userDefault:require("../../src/images/usersDefault.svg"),
    // greenPlane:require("../../src/images/greenPlane.svg"),
    // planeWhite:require("../../src/images/planeWhite.svg"),
    // planeSearchGreen:require("../../src/images/planeSearchGreen.svg"), 
    // truckWhite:require("../../src/images/truckWhite.svg"),
    // shipSearch:require("../../src/images/shipSearch.svg"),
    // planeSearch:require("../../src/images/planeSearch.svg"),
    // truckSearch:require("../../src/images/trucker.svg"),
    // trainSearch:require("../../src/images/trainSearch.svg"),
    // planeSearchWhite:require("../../src/images/planeSearchWhite.svg"),
    // shipSearchWhite:require("../../src/images/shipSearchWhite.svg"),
    // truckSearchWhite:require("../../src/images/truckSearchWhite.svg"),
    // truckerPhoto:require("../../src/images/trucker-default.png"),
    // truckPicture:require("../../src/images/truckPicture.svg"),
    // truckline:require("../../src/images/truckline.svg"),
    // trucklineWhite:require("../../src/images/truckLineWhite.svg"),
    // trucklineBlack:require("../../src/images/truckLineBlack.svg"),
    // trucklineBlackBig: require("../../src/images/trucklineBlackBig.svg"),
    // truckWareHouse:require("../../src/images/truckWareHouse.svg"),
    // c88:require("../../src/images/c88.svg"),
    // gate:require("../../src/images/gate.svg"),
    // borderGate:require("../../src/images/borderGate.svg"),
    // borderGateRed:require("../../src/images/borderGateRed.svg"),
    // errorIcon:require("../../src/images/ErrorIcon.svg"),
    // warningIcon:require("../../src/images/WarningIcon.svg"),
    // clearIcon:require("../../src/images/clear.svg"),
    // b3:require("../../src/images/b3.svg"),
    // shipDefault:require("../../src/images/shipDefault.svg"),
    // downArrowEta:require("../../src/images/downArrowEta.svg"),
    // upArrowEta:require("../../src/images/upArrowEta.svg"),
    // downArrowEtati:require("../../src/images/downArrowEta-ti.svg"),
    // downArrowEtajbh:require("../../src/images/downArrowEta-jbh.svg"),
    // downArrowEtajbhtdi:require("../../src/images/downArrowEta-jbhtdi.svg"),
    // downArrowEtajdl:require("../../src/images/downArrowEta-jdl.svg"),
    // downArrowEtaCSGP:require("../../src/images/downArrowEta-CSGP.svg"),
    // downArrowEtaefs:require("../../src/images/downArrowEta-Efs.svg"),
    // upArrowEtaefs:require("../../src/images/upArrowEta-efs.svg"),
    // upArrowEtaeti:require("../../src/images/upArrowEta-ti.svg"),
    // upArrowEtajdl:require("../../src/images/upArrowEta-jdl.svg"),
  
    // upArrowEtajbh:require("../../src/images/upArrowEta-jbh.svg"),
    // upArrowEtajbhtdi:require("../../src/images/upArrowEta-jbh-tdi.svg"),
    // downArrowBigTdi:require("../../src/images/downArrowTDI.svg"),
    // downArrowBigJBH:require("../../src/images/downArrowBigjbh.svg"),
    // downArrowBigCSGP:require("../../src/images/downArrowBigCSGP.svg"),
  
    // downArrowTealReport:require("../../src/images/downArrowTealReport.svg"),
    // genericVessel:require("../../src/images/genericVessel.jpeg"),
    // reportEye:require("../../src/images/reportEye.svg"),
    // excelIcon:require("../../src/images/excel.svg"),
    // close:require("../../src/images/close.svg"),
    // downArrowBigReportMore:require("../../src/images/downArrowReportMore.svg"),
    // upArrowBigReportLess:require("../../src/images/upArrowReportLess.svg"),
    // visaLogo: require("../../src/images/visa-logo.svg"),
    // mastercard: require("../../src/images/mastercard.svg"),
    // calendar: require("../../src/images/calendar.svg"),
    // successGreenCheckMark: require("../../src/images/success-green-check-mark.svg"),
    // reportEyeTI:require("../../src/images/reportEyeTI.svg"),
    // reportEyeJBH:require("../../src/images/reportEyeJBH.svg"),
    // reportEyeCSGP:require("../../src/images/reportEyeCSGP.svg"),
  
    // reportEyeEFS:require("../../src/images/reportEyeEfs.svg"),
    // reportEyeJBHTDI:require("../../src/images/reportEyeJBHTDI.svg"),
    // reportEyeJDL:require("../../src/images/reportEyeJDL.svg"),
    // planeSearchReport:require("../../src/images/planeSearchReport.svg"),
    // reportEyeWhite:require("../../src/images/reportEyeWhite.svg"),
    // reportEyeJBHReport:require("../../src/images/reportEyeJBHReport.svg"),
    // reportEyeTIReport:require("../../src/images/reportEyeTIReport.svg"),
    // reportEyeJDLReport:require("../../src/images/reportEyeJDLReport.svg"),
    // reportEyeJBHTDIReport:require("../../src/images/reportEyeJBHTDIReport.svg"),
    // reportEyeEFSReport:require("../../src/images/reportEyeEFSReport.svg"),
    // reportEyeCSGPReport:require("../../src/images/reportEyeCSGPReport.svg"),
    // checkmark:require("../../src/images/checkmark.svg"),
  
  
  
  }
  
  export default Images;
  